# Generated by Django 2.1.2 on 2018-10-27 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sessionfrom', models.TimeField()),
                ('sessionto', models.TimeField()),
                ('sessionDate', models.DateField()),
                ('studentstatus', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='College',
            fields=[
                ('collegeCode', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='College Code')),
                ('collegeName', models.CharField(blank=True, max_length=20, verbose_name='Name')),
                ('collegeAdress', models.CharField(blank=True, max_length=200, verbose_name='Address')),
                ('collegeLandLineNumber', models.CharField(blank=True, max_length=20, verbose_name='Land Line Number')),
                ('collegeSubStart', models.DateTimeField(blank=True, verbose_name='Subscription Start Date')),
                ('collegeSubEnd', models.DateTimeField(blank=True, verbose_name='Subscription End Date')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courceName', models.CharField(blank=True, max_length=200, verbose_name='Name')),
                ('courceDomain', models.CharField(blank=True, max_length=20, verbose_name='Domain')),
            ],
        ),
        migrations.CreateModel(
            name='Incharge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Lecturers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LecturerName', models.CharField(default='None', max_length=200)),
                ('LecturerUsername', models.CharField(default='None', max_length=200, unique=True)),
                ('LecturerPassword', models.CharField(default='pass', max_length=200)),
                ('salt', models.CharField(default='pass', max_length=200)),
                ('token', models.CharField(default='pass', max_length=512)),
                ('LastPasswordChange', models.DateTimeField()),
                ('collegeFK', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cuserauth.College')),
            ],
        ),
        migrations.CreateModel(
            name='Offerd_course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(default=0)),
                ('start', models.DateTimeField(blank=True)),
                ('end', models.DateTimeField(blank=True)),
                ('collegeFK', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cuserauth.College')),
                ('courseFK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cuserauth.Course')),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sectionName', models.CharField(max_length=5)),
                ('year', models.IntegerField(default=0)),
                ('collegeFK', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cuserauth.College')),
                ('courseFK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cuserauth.Course')),
            ],
        ),
        migrations.CreateModel(
            name='StudentInfo',
            fields=[
                ('StudentRollNo', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('studentName', models.CharField(max_length=20)),
                ('motherName', models.CharField(max_length=20)),
                ('fatherName', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=50)),
                ('fatherEmail', models.EmailField(max_length=50, null=True)),
                ('studentPhone', models.CharField(max_length=10)),
                ('fatherPhone', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('subjectCode', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('subjectName', models.CharField(max_length=20)),
                ('subjectYear', models.IntegerField()),
                ('courseFK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cuserauth.Course')),
            ],
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('studentInfoFK', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='cuserauth.StudentInfo')),
                ('year', models.IntegerField()),
                ('collegeFK', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cuserauth.College')),
                ('courseFK', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cuserauth.Offerd_course')),
                ('sectionFK', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cuserauth.Section')),
            ],
        ),
        migrations.AddField(
            model_name='incharge',
            name='lecturerFK',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cuserauth.Lecturers'),
        ),
        migrations.AddField(
            model_name='incharge',
            name='sectionFK',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cuserauth.Section'),
        ),
        migrations.AddField(
            model_name='incharge',
            name='subjectFK',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cuserauth.Subjects'),
        ),
        migrations.AlterUniqueTogether(
            name='course',
            unique_together={('courceName', 'courceDomain')},
        ),
        migrations.AddField(
            model_name='attendence',
            name='subjectFK',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cuserauth.Subjects'),
        ),
        migrations.AlterUniqueTogether(
            name='subjects',
            unique_together={('courseFK', 'subjectCode')},
        ),
        migrations.AlterUniqueTogether(
            name='section',
            unique_together={('collegeFK', 'courseFK', 'sectionName', 'year')},
        ),
        migrations.AlterUniqueTogether(
            name='offerd_course',
            unique_together={('collegeFK', 'courseFK')},
        ),
        migrations.AlterUniqueTogether(
            name='incharge',
            unique_together={('lecturerFK', 'sectionFK', 'subjectFK')},
        ),
        migrations.AddField(
            model_name='attendence',
            name='studentFK',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cuserauth.Students'),
        ),
        migrations.AlterUniqueTogether(
            name='students',
            unique_together={('studentInfoFK', 'courseFK', 'collegeFK', 'year')},
        ),
    ]
