# Generated by Django 2.1 on 2018-09-20 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='attendence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cfrom', models.TimeField()),
                ('cto', models.TimeField()),
                ('date', models.DateField()),
                ('status', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='college',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('sub_start', models.DateTimeField(blank=True)),
                ('sub_end', models.DateTimeField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('domain', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Incharge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cuserauth.college')),
            ],
        ),
        migrations.CreateModel(
            name='offerd_course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cuserauth.college')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cuserauth.course')),
            ],
        ),
        migrations.CreateModel(
            name='students',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sname', models.CharField(max_length=200)),
                ('parent', models.CharField(max_length=200)),
                ('phones', models.CharField(max_length=200)),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cuserauth.college')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cuserauth.course')),
            ],
        ),
        migrations.CreateModel(
            name='subjects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sname', models.CharField(max_length=200)),
                ('year', models.IntegerField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cuserauth.course')),
            ],
        ),
        migrations.AddField(
            model_name='incharge',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cuserauth.subjects'),
        ),
        migrations.AddField(
            model_name='attendence',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cuserauth.students'),
        ),
        migrations.AddField(
            model_name='attendence',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cuserauth.subjects'),
        ),
    ]
