# Generated by Django 2.1.2 on 2018-10-05 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cuserauth', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='college',
            old_name='college_id',
            new_name='coll_number',
        ),
    ]
