# Generated by Django 2.1.1 on 2018-10-03 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuserauth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offerd_course',
            name='end',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='offerd_course',
            name='start',
            field=models.DateTimeField(blank=True),
        ),
    ]
