# Generated by Django 2.1 on 2018-10-07 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cuserauth', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='students',
            unique_together={('StudentRollNo', 'courseFK', 'collegeFK', 'year')},
        ),
    ]
