# Generated by Django 2.1 on 2018-10-07 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuserauth', '0002_auto_20181007_0505'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecturers',
            name='salt',
            field=models.CharField(default='pass', max_length=200),
        ),
    ]
