# Generated by Django 2.1.2 on 2018-10-05 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cuserauth', '0002_auto_20181005_2256'),
    ]

    operations = [
        migrations.RenameField(
            model_name='college',
            old_name='coll_number',
            new_name='college_id',
        ),
    ]
