# Generated by Django 2.1 on 2018-10-07 08:09

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('cuserauth', '0003_lecturers_salt'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecturers',
            name='LastPasswordChange',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 7, 8, 9, 58, 988224, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lecturers',
            name='toaken',
            field=models.CharField(default='pass', max_length=512),
        ),
    ]
